package generator

import (
	"encoding/json"

	apiextensionsv2 "github.com/crossplane/crossplane/v2/apis/apiextensions/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"
)

// MarshalXRDToYAML renders a clean apply-ready XRD YAML.
// It hides the Status field and preserves lowercase JSON/YAML field names.
func MarshalXRDToYAML(xrd *apiextensionsv2.CompositeResourceDefinition) ([]byte, error) {

	// Wrap only the fields we want in the output, omitting Status
	// This prevents Crossplane's autogenerated Status fields from appearing in YAML
	p := struct {
		APIVersion string                                          `json:"apiVersion"`
		Kind       string                                          `json:"kind"`
		Metadata   metav1.ObjectMeta                               `json:"metadata"`
		Spec       apiextensionsv2.CompositeResourceDefinitionSpec `json:"spec"`
	}{
		APIVersion: xrd.TypeMeta.APIVersion,
		Kind:       xrd.TypeMeta.Kind,
		Metadata:   xrd.ObjectMeta,
		Spec:       xrd.Spec,
	}

	// Marshal to JSON first because:
	// 1. Go YAML libraries usually respect only 'yaml' tags.
	// 2. Most Kubernetes/Crossplane structs only have 'json' tags, not 'yaml'.
	// 3. This ensures all nested structs (e.g., ObjectMeta) use lowercase field names.
	jsonBytes, err := json.Marshal(p)
	if err != nil {
		return nil, err
	}

	// Convert JSON -> YAML
	// The JSON field names are already correct (lowercase), so YAML will preserve them.
	yamlBytes, err := yaml.JSONToYAML(jsonBytes)
	if err != nil {
		return nil, err
	}

	return yamlBytes, nil
}
